server:
  port: 80
  servlet:
    context-path: /runner

spring:
  jpa:
    database: oracle
    hibernate: 
      ddl-auto: update
    show-sql: true

logging:
  file:
    path: /log
    name: app-log
  level:
    com.hacademy.runner: debug

#spring: 
#  datasource: 
#    url: jdbc:h2:~/db/h2;AUTO_SERVER=TRUE
#    username: fs
#    password: fs
#    dbcp2: 
#      max-total: 20
#    driver-class-name: org.h2.Driver
#  h2: 
#    console: 
#      path: /console
#      enabled: true
#  resources:
#    static-locations:
